---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lucas.
--- DateTime: 09/02/2021 01:58
---


local locateBlip = {
    { "Clothes",-1841.62,-1199.65,14.31,366,4,0.7,355.0 },
    { "Safezone",-1851.58,-1233.75,13.03,280,2,0.7,355.0 },
    { "Fuzil",-1820.25,-1213.1,13.02,150,4,0.7,355.0 },
    { "Pistola",-1825.23,-1209.14,13.02,110,4,0.7,355.0 },
    { "Arena5x5",-1810.39,-1208.09,14.31,163,4,0.7,355.0 },
    { "FreeForAll",-1814.29,-1213.07,13.02,119,4,0.7,355.0 },
}

local blips = {
    { 1775.44,3706.6,34.27,119,4,0.7,"[PVP] Pistola" },
    { 1006.75,2366.65,55.57,119,4,0.7,"[PVP] Fuzil" },
}

CreateThread(function()
    for _,v in pairs(locateBlip) do
        local blip = AddBlipForCoord(v[2],v[3],v[4])
        SetBlipSprite(blip,v[5])
        SetBlipAsShortRange(blip,true)
        SetBlipColour(blip,v[6])
        SetBlipScale(blip,v[7])
        SetBlipDisplay(blip,5)
        BeginTextCommandSetBlipName("STRING")
        AddTextComponentString(v[1])
        EndTextCommandSetBlipName(blip)
    end

    for _,v in pairs(blips) do
        local blip = AddBlipForCoord(v[1],v[2],v[3])
        SetBlipSprite(blip,v[4])
        SetBlipAsShortRange(blip,true)
        SetBlipColour(blip,v[5])
        SetBlipScale(blip,v[6])
        BeginTextCommandSetBlipName("STRING")
        AddTextComponentString(v[7])
        EndTextCommandSetBlipName(blip)

        pistolZone = AddBlipForRadius(1775.44,3706.6,34.27,355.0)
        SetBlipAlpha(pistolZone, 70)
        SetBlipColour(pistolZone, 1)

        fuzilZone = AddBlipForRadius(1006.75,2366.65,55.57,355.0)
        SetBlipAlpha(fuzilZone, 70)
        SetBlipColour(fuzilZone, 1)

        safeZone = AddBlipForRadius(-1830.76,-1216.55,13.02,140.0)
        SetBlipAlpha(safeZone, 70)
        SetBlipColour(safeZone, 2)
    end
end)


