---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lucas.
--- DateTime: 09/02/2021 00:26
---

local freeForAll = 0

local pedList = {
  {
      ["coords"] = { -1825.57,-1208.69,13.02,208.08 },
      ["hash"] = 0xAD340F5A,
      ["hash2"] = "cs_orleans",
      ["name"] = "~r~[E]~w~ Pistol Zone",
      ["weapon"] = "WEAPON_PISTOL_MK2",
  },
  {
      ["coords"] = { -1819.66,-1213.11,13.02,92.4 },
      ["hash"] = 0x3C438CD2,
      ["hash2"] = "u_m_y_rsranger_01",
      ["name"] = "~r~[E]~w~ Fuzil Zone",
      ["weapon"] = "WEAPON_ASSAULTRIFLE_MK2",
  },
  {
      ["coords"] = { -1842.12,-1199.32,14.31,241.22 },
      ["hash"] = 0x348065F5,
      ["hash2"] = "u_m_y_imporage",
      ["name"] = "~r~[E]~w~ Roupas",
      ["weapon"] = nil,
  },
  {
      ["coords"] = { -1813.8,-1213.42,13.02,42.69 },
      ["hash"] = 0x6C19E962,
      ["hash2"] = "u_m_m_streetart_01",
      ["name"] = nil,
      ["weapon"] = nil,
  },
  {
      ["coords"] = { -1820.04,-1220.51,13.02,27.38 },
      ["hash"] = 0x64611296,
      ["hash2"] = "s_m_m_movalien_01",
      ["name"] = "~y~[E]~w~ Gungame ~y~[VIP]",
      ["weapon"] = nil,
  },
  {
      ["coords"] = { -1845.02,-1195.48,19.19,150.29 },
      ["hash"] = 0x91CA3E2C,
      ["hash2"] = "a_m_y_juggalo_01",
      ["name"] = "~r~[E]~w~ Barbearia",
      ["weapon"] = nil,
  },
}

Citizen.CreateThread(function()
    for k,v in pairs(pedList) do
        RequestModel(GetHashKey(v["hash2"]))
        while not HasModelLoaded(GetHashKey(v["hash2"])) do
            Citizen.Wait(10)
        end

        local ped = CreatePed(4,v["hash"],v["coords"][1],v["coords"][2],v["coords"][3] - 1,v["coords"][4],false,true)
        FreezeEntityPosition(ped,true)
        SetEntityInvincible(ped,true)
        SetBlockingOfNonTemporaryEvents(ped,true)

        if v["weapon"] ~= nil then
            GiveWeaponToPed(ped,GetHashKey(v["weapon"]),1,true,true)
        end
    end

    Citizen.Wait(1000)

    while true do
        local idle = 1000
        local ped = PlayerPedId()
        local coords = GetEntityCoords(ped)

        for k,v in pairs(pedList) do
            local distance = #(coords - vec3(v["coords"][1],v["coords"][2],v["coords"][3]))
            if distance <= 3 then
                idle = 4
                if v["name"] ~= nil then
                    drawSimple(v["coords"][1],v["coords"][2],v["coords"][3] + 1,v["name"],500)
                else
                    drawComplex(v["coords"][1],v["coords"][2],v["coords"][3] + 1,"~r~Playing: ~w~"..freeForAll.."/10\n~r~[E] ~w~Free For All ~r~[B/TEST]",500,0.055)
                end
            end
        end

        local pistol = #(coords - vector3(-1825.41,-1209.2,13.02))
        if pistol <= 1.5 then
            idle = 4
            if IsControlJustPressed(0,38) then
                TriggerEvent("smash-common:zonePistol")
            end
        end

        local fuzil = #(coords - vector3(-1819.66,-1213.11,13.02))
        if fuzil <= 1.5 then
            idle = 4
            if IsControlJustPressed(0,38) then
                TriggerEvent("smash-common:zoneFuzil")
            end
        end

        Citizen.Wait(idle)
    end
end)

RegisterNetEvent("ffaUpdate")
AddEventHandler("ffaUpdate",function(status)
    freeForAll = status
    if freeForAll == nil then
        freeForAll = 0
    end
end)